#!/bin/sh -e

if [ "$1" = "purge" ] && [ -e /usr/share/debconf/confmodule ]; then
  # Source debconf library
  . /usr/share/debconf/confmodule
  # Remove my changes to the db 
  echo "Purging debconf for bitcoinxt"
  db_purge || true
fi
