#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

export BITCOIN_CONF="/etc/bitcoinxt/bitcoin.conf"

# add random rpc password to bitcoin.conf, if there isn't one.
if ! grep -q '^rpcpassword=' $BITCOIN_CONF; then
    echo "Adding a random rcp password to $BITCOIN_CONF"
    echo "rpcpassword=$(xxd -l 17 -p /dev/urandom)" >> $BITCOIN_CONF
fi

# add users
adduser --system --group --quiet bitcoin

# cleanup permissions
chown root:root /usr/bin/bitcoinxt*
chown root:root /lib/systemd/system/bitcoinxtd.service
chown root:root /etc/bitcoinxt
chown bitcoin:bitcoin /etc/bitcoinxt/bitcoin.conf
chmod ug+r /etc/bitcoinxt/bitcoin.conf 
chmod u+w /etc/bitcoinxt/bitcoin.conf
chmod o-rw /etc/bitcoinxt/bitcoin.conf 
chown -R bitcoin:bitcoin /var/lib/bitcoinxt
chmod u+rwx /var/lib/bitcoinxt

# enable and start bitcoinxtd service if systemctl exists and is executable
if [ -x "/bin/systemctl" ]; then
    db_input high bitcoinxt/start_service || true
    db_go || true
    db_get bitcoinxt/start_service 
    if [ "$RET" = "true" ]; then
        echo "Enabling bitcoinxtd.service"
    	/bin/systemctl enable bitcoinxtd.service
        echo "Starting bitcoinxtd.service"
    	/bin/systemctl start bitcoinxtd.service
    else
        echo "The bitcoinxtd.service NOT enabled or started."
    fi
else
    echo "The file '/bin/systemctl' is not executable or found, bitcoinxtd service not automatically enabled or started" 
fi

# ask which network to connect to
db_input high bitcoinxt/select_network || true
db_go || true
db_get bitcoinxt/select_network
if [ "$RET" = "Bitcoin (BTC)" ]; then
    if grep -q '^uahftime' $BITCOIN_CONF; then
        sed -i 's/^uahftime.*/uahftime=0/' $BITCOIN_CONF
        echo "BTC selected: Setting uahftime=0 in $BITCOIN_CONF"
    else
        echo "uahftime=0" >> $BITCOIN_CONF
        echo "BTC selected: Adding uahftime=0 to $BITCOIN_CONF"
    fi;
else
    if grep -q '^uahftime' $BITCOIN_CONF; then
        sed -i 's/^uahftime.*//' $BITCOIN_CONF
        echo "BCH selected: Removing uahftime from $BITCOIN_CONF"
    else
        echo "BCH selected: No configuration change needed."
    fi;
fi
